package com.collect_up.c_up.helpers;

/**
 * Created by collect-up3 on 9/19/2016.
 */
public enum fragmentType {
  PROFILE, HOME, BUSINESS, TIMELINE, SEARCH, NOTIFICATIONS, CONVERSATIONS,
  COMPLEX, PRODUCT, CONTACTS,
  FINDPEOPLE, PREFERENCE, DISPLAYPOST,
  NEWPOST, EDITPOST, EDITPRODUCT, TAG_PEOPLE,
  ADD_BUSINESS_COMPLEX, ADD_COMPLEX_BUSINESS,
  NEWBUSINESS, NEWEVENT, NEWCOMPLEX, NEWPRODUCT,
  EDITBUSINESS, EDITCOMPLEX, EDITPERSON,
  ADD_MANAGER, REQUESTS, SHARE, SET_ADMIN,
  CHATCONTACTS, FOLLOWNFOLLOWING, LIKES,
  CHAT, HASHTAG, GROUPCHAT, GROUPCHAT_INIT, GROUPCHAT_INFO,
  PREF_NOTIFS, PREF_BLOCKLIST, PREF_DENIEDLIST, PREF_MANAGE_STICKER, PREF_ALLSTICKERS, PREF_TWOSTEP, PREF_TWOSTEP_ENTER, PREF_SESSIONMANAGER, PREF_PRIVACY,
  TWOSTEP_ENABLE

}
